///|
/// `object` is used to define the properties schema of a request
/// and represents a map of strings to Json values.
pub let object : Json = "object".to_json()

///|
/// `number` is used to define the properties schema of a request
/// and represents a floating point number.
pub let number : Json = "number".to_json()

///|
/// `integer` is used to define the properties schema of a request
/// and represents an integer number.
pub let integer : Json = "integer".to_json()

///|
/// `string` is used to define the properties schema of a request
/// and represents a string value.
pub let string : Json = "string".to_json()

///|
/// `array` is used to define the properties schema of a request
/// and represents an array of values.
pub let array : Json = "array".to_json()

///|
/// `boolean` is used to define the properties schema of a request
/// and represents a boolean value.
pub let boolean : Json = "boolean".to_json()
